### ISSUE TITLE
Attribute Error when making report

### ISSUE THREAD

**Issue by crip1163** [epi2me-labs/wf-alignment#19]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20.04.6 LTS

### Workflow Version

0.6.2

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

5.1.3

### Workflow Execution - CLI Execution Profile

None

### What happened?

For certain datasets, the wf-alignment pipeline is unable to run the "make report" function. I'm not sure why this happens, since it does not happen for all datasets.  It seems to be related to making a histogram and having an object that is not 'round'.

### Relevant log output

```shell
N E X T F L O W  ~  version 23.04.2
Launching `/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/main.nf` [pedantic_kirch] DSL2 - revision: 6c3a60c0a1
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-alignment v0.6.2
--------------------------------------------------------------------------------
Core Nextflow options
  runName        : pedantic_kirch
  containerEngine: docker
  launchDir      : /data/Charley/EPI2ME/instances/wf-alignment_01HFF687D6HGXMMZSNZCEG42EH
  workDir        : /data/Charley/EPI2ME/instances/wf-alignment_01HFF687D6HGXMMZSNZCEG42EH/work
  projectDir     : /data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment
  userName       : grid
  profile        : standard
  configFiles    : /data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/nextflow.config
Input Options
  fastq          : /data/231019_WHOCollab_ViralStocks/10_4_CFU_Ad5Back/20231019_1757_X2_FAX85227_85dadf96/fastq_pass
  references     : /data/Charley/2023_WHO_Collab_Sequences
Output Options
  out_dir        : /data/Charley/EPI2ME/instances/wf-alignment_01HFF687D6HGXMMZSNZCEG42EH/output
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-alignment for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-alignment v0.6.2.
--------------------------------------------------------------------------------
Searching input for [.fastq, .fastq.gz, .fq, .fq.gz] files.
[92/e34351] Submitted process > pipeline:process_references:combine
[a3/426252] Submitted process > pipeline:getVersions
[3a/31a05a] Submitted process > pipeline:process_references:fx2tab (1)
[af/40cd90] Submitted process > pipeline:getParams
[cf/eb9513] Submitted process > pipeline:process_references:fx2tab (2)
[a3/7a2772] Submitted process > pipeline:process_references:fx2tab (7)
[73/53683d] Submitted process > pipeline:process_references:fx2tab (3)
[08/5c4526] Submitted process > pipeline:process_references:fx2tab (6)
[e3/f34c3f] Submitted process > pipeline:process_references:fx2tab (8)
[18/18c412] Submitted process > pipeline:process_references:fx2tab (4)
[11/e8eb1e] Submitted process > pipeline:process_references:fx2tab (5)
[d4/294d19] Submitted process > pipeline:process_references:fx2tab (9)
[e1/4394de] Submitted process > pipeline:process_references:fx2tab (13)
[bb/6b54ba] Submitted process > pipeline:process_references:fx2tab (10)
[4f/a87935] Submitted process > pipeline:process_references:fx2tab (18)
[8b/8533e9] Submitted process > pipeline:process_references:fx2tab (11)
[84/ca2c1f] Submitted process > pipeline:process_references:fx2tab (12)
[3b/e58f1c] Submitted process > pipeline:process_references:fx2tab (14)
[ba/0cf8e5] Submitted process > pipeline:process_references:fx2tab (16)
[f1/8b12a0] Submitted process > pipeline:process_references:fx2tab (15)
[de/e26347] Submitted process > pipeline:process_references:fx2tab (17)
[ea/99e72d] Submitted process > pipeline:process_references:fx2tab (19)
[42/824b28] Submitted process > pipeline:process_references:fx2tab (20)
[0a/0eff8b] Submitted process > pipeline:process_references:fx2tab (21)
[2e/9b98d7] Submitted process > pipeline:process_references:fx2tab (22)
[b7/55b368] Submitted process > fastcat (1)
[2b/fef149] Submitted process > pipeline:addStepsColumn
[9b/a27c87] Submitted process > pipeline:alignReads (1)
[a8/ccfb01] Submitted process > pipeline:indexBam (1)
[c7/095025] Submitted process > pipeline:bamstats (1)
[52/01d3ba] Submitted process > pipeline:readDepthPerRef (1)
[85/9a475c] Submitted process > configure_jbrowse
[76/386dce] Submitted process > output (1)
[15/2a9fc6] Submitted process > output (3)
[9d/baef9c] Submitted process > output (2)
[15/0e9cd4] Submitted process > output (5)
[3a/97bcd4] Submitted process > output (4)
[95/dfdb9e] Submitted process > pipeline:makeReport
ERROR ~ Error executing process > 'pipeline:makeReport'
Caused by:
  Process `pipeline:makeReport` terminated with an error exit status (1)
Command executed:
  workflow-glue report         --name wf-alignment         --stats_dir readstats         --flagstat_dir flagstat         --refnames_dir refnames         --versions versions.txt         --params params.json         --depths_dir depths
Command exit status:
  1
Command output:
  (empty)
Command error:
  [18:00:26 - matplotlib.font_manager] generated new fontManager
  [18:00:27 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/bin/workflow-glue", line 7, in <module>
      cli()
    File "/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report.py", line 62, in main
      sections.quality(report, stats_df, sanitizer)
    File "/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report_utils/sections.py", line 279, in quality
      plt = histogram_with_mean_and_median(
    File "/data/Charley/EPI2ME/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report_utils/sections.py", line 44, in histogram_with_mean_and_median
      f"Mean: {series.mean().round(round_digits)}. "
  AttributeError: 'float' object has no attribute 'round'
Work dir:
  /data/Charley/EPI2ME/instances/wf-alignment_01HFF687D6HGXMMZSNZCEG42EH/work/95/dfdb9ea76be2bf852485ebf410aaef
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
 -- Check '/data/Charley/EPI2ME/instances/wf-alignment_01HFF687D6HGXMMZSNZCEG42EH/nextflow.log' file for details
```

**Comment by julibeg** [comment]
Hi @crip1163, would you be able to share one of these datasets?

**Comment by crip1163** [comment]
Hi @julibeg.  Possibly.  What would be the easiest way to share the files?

**Comment by jaredmychal** [comment]
I also am having this issue.

```
ERROR ~ Error executing process > 'pipeline:makeReport'

Caused by:
  Process `pipeline:makeReport` terminated with an error exit status (1)

Command executed:

  workflow-glue report         --name wf-alignment         --stats_dir readstats         --flagstat_dir flagstat         --refnames_dir refnames         --versions versions.txt         --params params.json         --depths_dir depths

Command exit status:
  1

Command output:
  (empty)

Command error:
  [00:46:51 - matplotlib.font_manager] generated new fontManager
  [00:46:51 - workflow_glue] Starting entrypoint.
  Traceback (most recent call last):
    File "/home/jared/.nextflow/assets/epi2me-labs/wf-alignment/bin/workflow-glue", line 7, in <module>
      cli()
    File "/home/jared/.nextflow/assets/epi2me-labs/wf-alignment/bin/workflow_glue/__init__.py", line 72, in cli
      args.func(args)
    File "/home/jared/.nextflow/assets/epi2me-labs/wf-alignment/bin/workflow_glue/report.py", line 64, in main
      sections.read_coverage(report, stats_df_mapped, sanitizer)
    File "/home/jared/.nextflow/assets/epi2me-labs/wf-alignment/bin/workflow_glue/report_utils/sections.py", line 379, in read_coverage
      plt = histogram_with_mean_and_median(
    File "/home/jared/.nextflow/assets/epi2me-labs/wf-alignment/bin/workflow_glue/report_utils/sections.py", line 44, in histogram_with_mean_and_median
      f"Mean: {series.mean().round(round_digits)}. "
  AttributeError: 'float' object has no attribute 'round'

Work dir:
  /mnt/d/Epi2meLabs/work/8f/4f9bbf647e91dcd411a32f1d7502dc
```

**Comment by julibeg** [comment]
Hi @crip1163 and @jaredmychal, could you please try the newest version of the workflow (v0.6.3) and see if the problem persists? Thanks!

**Comment by crip1163** [comment]
@julibeg This fixed the issue!  Thank you so much for addressing this!
