### ISSUE TITLE
Not able to run the programme

### ISSUE THREAD

**Issue by mariasolruiz** [epi2me-labs/wf-alignment#34]
### Operating System

Other Linux (please specify below)

### Other Linux

Ubuntu 20.04.2 LTS 

### Workflow Version

 N E X T F L O W  ~  version 24.04.4

### Workflow Execution

Command line (Cluster)

### CLI command run

srun nextflow run epi2me-labs/wf-alignment --help

### Workflow Execution - CLI Execution Profile

None

### What happened?

I was trying to run the demo data, and it failed. When I tried to run --h (visualize the help) it was not working anymore (it had worked the first time).
I then tried to run other epi2me workflows (i.e. transcriptomes, human variation) and I was able to run the help in both cases, so it looks like a specific problem with the alignment workflow

### Relevant log output

```shell
N E X T F L O W   ~  version 24.04.4

Pulling epi2me-labs/wf-alignment ...
ERROR ~ Unexpected error [NullPointerException]

 -- Check '.nextflow.log' file for details
srun: error: nodo15: task 0: Exited with exit code 1



Aug-13 15:53:14.023 [main] DEBUG nextflow.cli.Launcher - $> nextflow run epi2me-labs/wf-alignment --help
Aug-13 15:53:14.229 [main] DEBUG nextflow.cli.CmdRun - N E X T F L O W  ~  version 24.04.4
Aug-13 15:53:14.268 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/home/msruiz/.nextflow/plugins; core-plugins: nf-amazon@2.5.3,nf-azure@1.6.1,nf-cloudcache@0.4.1,nf-codecommit@0.2.1,nf-console@1.1.3,nf-ga4gh@1.3.0,nf-google@1.13.2-patch1,nf-tower@1.9.1,nf-wave@1.4.2-patch1
Aug-13 15:53:14.294 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Aug-13 15:53:14.296 [main] INFO  o.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Aug-13 15:53:14.303 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.12.0 in 'deployment' mode
Aug-13 15:53:14.330 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Aug-13 15:53:14.355 [main] DEBUG nextflow.scm.ProviderConfig - Using SCM config path: /home/msruiz/.nextflow/scm
Aug-13 15:53:14.395 [main] DEBUG nextflow.scm.AssetManager - Project manifest does not exist: /home/msruiz/.nextflow/assets/epi2me-labs/wf-alignment/nextflow.config (No such file or directory)
Aug-13 15:53:14.406 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/msruiz/.nextflow/assets/epi2me-labs/wf-alignment/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-alignment.git
Aug-13 15:53:14.474 [main] DEBUG nextflow.scm.RepositoryFactory - Found Git repository result: [RepositoryFactory]
Aug-13 15:53:14.493 [main] DEBUG nextflow.scm.AssetManager - Git config: /home/msruiz/.nextflow/assets/epi2me-labs/wf-alignment/.git/config; branch: master; remote: origin; url: https://github.com/epi2me-labs/wf-alignment.git
Aug-13 15:53:14.494 [main] INFO  nextflow.cli.CmdRun - Pulling epi2me-labs/wf-alignment ...
Aug-13 15:53:14.496 [main] DEBUG nextflow.scm.AssetManager - Pull pipeline epi2me-labs/wf-alignment  -- Using local path: /home/msruiz/.nextflow/assets/epi2me-labs/wf-alignment
Aug-13 15:53:14.761 [main] ERROR nextflow.cli.Launcher - @unknown
java.lang.NullPointerException: null
        at nextflow.scm.AssetManager.getCurrentRevisionAndName(AssetManager.groovy:715)
        at nextflow.scm.AssetManager.download(AssetManager.groovy:636)
        at nextflow.cli.CmdRun.getScriptFile0(CmdRun.groovy:580)
        at nextflow.cli.CmdRun.getScriptFile(CmdRun.groovy:513)
        at nextflow.cli.CmdRun.run(CmdRun.groovy:321)
        at nextflow.cli.Launcher.run(Launcher.groovy:503)
        at nextflow.cli.Launcher.main(Launcher.groovy:657)
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by cjw85** [comment]
The errors look to me to be issues with nextflow itself and not the workflow itself, possibly convoluted with your slurm execution environment. Are you able to run https://github.com/nextflow-io/hello?
