### ISSUE TITLE
Error running wf-alignment: Reference '211000022279122' not found in the provided reference files

### ISSUE THREAD

**Issue by MujeebQadiri** [epi2me-labs/wf-alignment#36]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.2.1

### Workflow Execution

EPI2ME Desktop (Local)

### EPI2ME Version

v5.2.1

### Workflow Execution - CLI Execution Profile

None

### What happened?

I have tried aligning my long-read sequencing of cDNA using wf-alignment to check the genome coverage/depth and I am running into an error: `ValueError: Reference '211000022279122' not found in the provided reference files ['Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa'].`

I have checked my reference genome file for this reference and it does exist.

```
$ grep "211000022279122" Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa 
>211000022279122 dna:primary_assembly primary_assembly:BDGP6.46:211000022279122:1:2383:1 REF
```

Any ideas would be appreciated, thank you!

Best,
Mujeeb Qadiri

### Relevant log output

```shell
If you use epi2me-labs/wf-alignment for your analysis please cite:
* The nf-core framework
https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-alignment v1.2.1.
--------------------------------------------------------------------------------
Searching input for [.bam, .ubam] files.
[df/8bc7f2] Submitted process > pipeline:getParams
[d9/1349bc] Submitted process > checkBamHeaders (1)
[f8/d0f9df] Submitted process > pipeline:process_references:fx2tab (1)
[84/864049] Submitted process > pipeline:process_references:combine
[29/a97d1b] Submitted process > pipeline:getVersions
[8d/5db6d7] Submitted process > output (1)
[33/f7d27e] Submitted process > output (3)
[b1/49698c] Submitted process > output (2)
[4f/e88385] Submitted process > pipeline:makeMMIndex
[de/fd16d7] Submitted process > pipeline:addStepsColumn
[c3/9cb7d7] Submitted process > validateIndex (1)
[9b/de868e] Submitted process > output (4)
[11/7fb282] Submitted process > output (5)
[bc/ae4428] Submitted process > pipeline:bamstats (1)
[22/22ca15] Submitted process > pipeline:readDepthPerRef (1)
[de/578e62] Submitted process > output (6)
[a9/aefa66] Submitted process > output (7)
[ff/30c889] Submitted process > pipeline:configure_igv (1)
[2c/cdea83] Submitted process > output (8)
[22/034e39] Submitted process > output (14)
[a9/298adb] Submitted process > output (12)
[ab/e8237b] Submitted process > output (13)
[0f/7cb5be] Submitted process > output (11)
[d0/d3594a] Submitted process > output (9)
[98/273ddd] Submitted process > output (10)
[3f/4b3e5d] Submitted process > output (15)
[36/666cf2] Submitted process > pipeline:collectFilesInDir (1)
[cf/799773] Submitted process > pipeline:makeReport
[cf/799773] NOTE: Process `pipeline:makeReport` terminated with an error exit status (1) -- Execution is retried (1)
[c3/6fdc3b] Re-submitted process > pipeline:makeReport
ERROR ~ Error executing process > 'pipeline:makeReport'
Caused by:
Process `pipeline:makeReport` terminated with an error exit status (1)
Command executed:
workflow-glue report --data per-sample-data --refnames_dir refnames --versions versions.txt --params params.json --wf-version v1.2.1
Command exit status:
1
Command output:
(empty)
Command error:
[19:17:03 - workflow_glue] Bootstrapping CLI.
[19:17:09 - matplotlib.font_manager] generated new fontManager
[19:17:09 - workflow_glue] Starting entrypoint.
Traceback (most recent call last):
File "/home/drsc-linux/epi2melabs/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report.py", line 47, in main
df["ref"].apply(lambda ref: refname2reffile[ref]).astype("category")
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/series.py", line 4771, in apply
return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/apply.py", line 1123, in apply
return self.apply_standard()
File "/opt/custflow/epi2meuser/conda/lib/python3.8/site-packages/pandas/core/apply.py", line 1174, in apply_standard
mapped = lib.map_infer(
File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
File "/home/drsc-linux/epi2melabs/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report.py", line 47, in <lambda>
df["ref"].apply(lambda ref: refname2reffile[ref]).astype("category")
KeyError: 211000022279122
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/drsc-linux/epi2melabs/workflows/epi2me-labs/wf-alignment/bin/workflow-glue", line 7, in <module>
cli()
File "/home/drsc-linux/epi2melabs/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/__init__.py", line 82, in cli
args.func(args)
File "/home/drsc-linux/epi2melabs/workflows/epi2me-labs/wf-alignment/bin/workflow_glue/report.py", line 51, in main
raise ValueError(
ValueError: Reference '211000022279122' not found in the provided reference files ['Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa'].
Work dir:
/home/drsc-linux/epi2melabs/instances/wf-alignment_01J9YG3Z0JZ633HEFM95WD9Y0Q/work/c3/6fdc3bfdf8f2b4f80f13c98cf886be
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
-- Check '/home/drsc-linux/epi2melabs/instances/wf-alignment_01J9YG3Z0JZ633HEFM95WD9Y0Q/nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by raquel-romao** [comment]
I have the same issue. Did you manage to find a solution @MujeebQadiri?

**Comment by julibeg** [comment]
Looks like this is a bug that occurs when the ID of a reference sequence is numeric and I'm sure it will be fixed soon. A temporary fix could be to rename all sequences in your reference, for example with

```
sed 's/^>/>_/' Drosophila_melanogaster.BDGP6.46.dna.toplevel.fa > IDs-with-underscores.fa
```

**Comment by nggvs** [comment]
Hi @MujeebQadiri,
This should have been fixed in version 1.2.2, please feel free to open a new issue if you find any other issue.
Thank you very much for using the workflow!
